### ISSUE TITLE
Meta Data Generation Failed!!! 

### ISSUE THREAD

**Issue by metadreamx** [magic-quill/ComfyUI_MagicQuill#15]
How Can We Fix This!!        

File "C:\Users\antho\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\antho\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\antho\AppData\Local\Temp\pip-build-env-tmb6crrq\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\antho\AppData\Local\Temp\pip-build-env-tmb6crrq\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\antho\AppData\Local\Temp\pip-build-env-tmb6crrq\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 669, in <module>
        File "<string>", line 663, in setup_package
        File "<string>", line 597, in configure_extension_modules
        File "C:\Users\antho\AppData\Local\Temp\pip-install-18jxx4ep\scikit-learn_522a5ccaa39749358244c5f4244749a5\sklearn\_build_utils\__init__.py", line 98, in cythonize_extensions
          return cythonize(
                 ^^^^^^^^^^
        File "C:\Users\antho\AppData\Local\Temp\pip-build-env-tmb6crrq\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1145, in cythonize
          result.get(99999)  # seconds
          ^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\multiprocessing\pool.py", line 774, in get
          raise self._value
      Cython.Compiler.Errors.CompileError: sklearn\_loss\_loss.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by Rion-beta-development** [comment]
same

**Comment by Rion-beta-development** [comment]
Error compiling Cython file:
      ------------------------------------------------------------
      ...
          void MurmurHash3_x64_128 (void *key, int len, cnp.uint32_t seed, void *out)

      cnp.import_array()


      cpdef cnp.uint32_t murmurhash3_int_u32(int key, unsigned int seed):
            ^
      ------------------------------------------------------------

      sklearn\utils\murmurhash.pyx:29:6: Function signature does not match previous declaration
      warning: sklearn\utils\murmurhash.pyx:36:37: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef cnp.uint32_t out
          MurmurHash3_x86_32(&key, sizeof(int), seed, &out)
          return out


      cpdef cnp.int32_t murmurhash3_int_s32(int key, unsigned int seed):
            ^
      ------------------------------------------------------------

      sklearn\utils\murmurhash.pyx:36:6: Function signature does not match previous declaration
      warning: sklearn\utils\murmurhash.pyx:43:40: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef cnp.int32_t out
          MurmurHash3_x86_32(&key, sizeof(int), seed, &out)
          return out


      cpdef cnp.uint32_t murmurhash3_bytes_u32(bytes key, unsigned int seed):
            ^
      ------------------------------------------------------------

      sklearn\utils\murmurhash.pyx:43:6: Function signature does not match previous declaration
      warning: sklearn\utils\murmurhash.pyx:50:39: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef cnp.uint32_t out
          MurmurHash3_x86_32(<char*> key, len(key), seed, &out)
          return out


      cpdef cnp.int32_t murmurhash3_bytes_s32(bytes key, unsigned int seed):
            ^
      ------------------------------------------------------------

      sklearn\utils\murmurhash.pyx:50:6: Function signature does not match previous declaration
      Traceback (most recent call last):
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sklearn\utils\murmurhash.pyx
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:245:34: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:257:28: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:263:35: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:271:37: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:278:33: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:284:30: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:968:31: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:999:38: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:1014:37: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:1029:45: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:1039:47: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      warning: C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\numpy\__init__.cython-30.pxd:1046:48: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
      Compiling sklearn\__check_build\_check_build.pyx because it changed.
      Compiling sklearn\_isotonic.pyx because it changed.
      Compiling sklearn\_loss\_loss.pyx because it changed.
      Compiling sklearn\cluster\_dbscan_inner.pyx because it changed.
      Compiling sklearn\cluster\_hierarchical_fast.pyx because it changed.
      Compiling sklearn\cluster\_k_means_common.pyx because it changed.
      Compiling sklearn\cluster\_k_means_lloyd.pyx because it changed.
      Compiling sklearn\cluster\_k_means_elkan.pyx because it changed.
      Compiling sklearn\cluster\_k_means_minibatch.pyx because it changed.
      Compiling sklearn\datasets\_svmlight_format_fast.pyx because it changed.
      Compiling sklearn\decomposition\_online_lda_fast.pyx because it changed.
      Compiling sklearn\decomposition\_cdnmf_fast.pyx because it changed.
      Compiling sklearn\ensemble\_gradient_boosting.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\_gradient_boosting.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\histogram.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\splitting.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\_binning.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\_predictor.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\_bitset.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\common.pyx because it changed.
      Compiling sklearn\ensemble\_hist_gradient_boosting\utils.pyx because it changed.
      Compiling sklearn\feature_extraction\_hashing_fast.pyx because it changed.
      Compiling sklearn\linear_model\_cd_fast.pyx because it changed.
      Compiling sklearn\linear_model\_sgd_fast.pyx because it changed.
      Compiling sklearn\linear_model\_sag_fast.pyx because it changed.
      Compiling sklearn\manifold\_utils.pyx because it changed.
      Compiling sklearn\manifold\_barnes_hut_tsne.pyx because it changed.
      Compiling sklearn\metrics\_pairwise_fast.pyx because it changed.
      Compiling sklearn\metrics\_dist_metrics.pyx because it changed.
      Compiling sklearn\metrics\cluster\_expected_mutual_info_fast.pyx because it changed.
      Compiling sklearn\metrics\_pairwise_distances_reduction\_datasets_pair.pyx because it changed.
      Compiling sklearn\metrics\_pairwise_distances_reduction\_middle_term_computer.pyx because it changed.
      Compiling sklearn\metrics\_pairwise_distances_reduction\_base.pyx because it changed.
      Compiling sklearn\metrics\_pairwise_distances_reduction\_argkmin.pyx because it changed.
      Compiling sklearn\metrics\_pairwise_distances_reduction\_radius_neighbors.pyx because it changed.
      Compiling sklearn\preprocessing\_csr_polynomial_expansion.pyx because it changed.
      Compiling sklearn\neighbors\_ball_tree.pyx because it changed.
      Compiling sklearn\neighbors\_kd_tree.pyx because it changed.
      Compiling sklearn\neighbors\_partition_nodes.pyx because it changed.
      Compiling sklearn\neighbors\_quad_tree.pyx because it changed.
      Compiling sklearn\svm\_newrand.pyx because it changed.
      Compiling sklearn\svm\_libsvm.pyx because it changed.
      Compiling sklearn\svm\_liblinear.pyx because it changed.
      Compiling sklearn\svm\_libsvm_sparse.pyx because it changed.
      Compiling sklearn\tree\_tree.pyx because it changed.
      Compiling sklearn\tree\_splitter.pyx because it changed.
      Compiling sklearn\tree\_criterion.pyx because it changed.
      Compiling sklearn\tree\_utils.pyx because it changed.
      Compiling sklearn\utils\sparsefuncs_fast.pyx because it changed.
      Compiling sklearn\utils\_cython_blas.pyx because it changed.
      Compiling sklearn\utils\arrayfuncs.pyx because it changed.
      Compiling sklearn\utils\murmurhash.pyx because it changed.
      Compiling sklearn\utils\_fast_dict.pyx because it changed.
      Compiling sklearn\utils\_openmp_helpers.pyx because it changed.
      Compiling sklearn\utils\_seq_dataset.pyx because it changed.
      Compiling sklearn\utils\_weight_vector.pyx because it changed.
      Compiling sklearn\utils\_random.pyx because it changed.
      Compiling sklearn\utils\_logistic_sigmoid.pyx because it changed.
      Compiling sklearn\utils\_readonly_array_wrapper.pyx because it changed.
      Compiling sklearn\utils\_typedefs.pyx because it changed.
      Compiling sklearn\utils\_heap.pyx because it changed.
      Compiling sklearn\utils\_sorting.pyx because it changed.
      Compiling sklearn\utils\_vector_sentinel.pyx because it changed.
      Compiling sklearn\utils\_isfinite.pyx because it changed.
      multiprocessing.pool.RemoteTraceback:
      """
      Traceback (most recent call last):
        File "C:\ProgramData\miniconda3\Lib\multiprocessing\pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
                          ^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\miniconda3\Lib\multiprocessing\pool.py", line 48, in mapstar
          return list(map(*args))
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sklearn\_loss\_loss.pyx
      """

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\Rion Dey\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      [ 1/64] Cythonizing sklearn\__check_build\_check_build.pyx
      [ 2/64] Cythonizing sklearn\_isotonic.pyx
      [ 3/64] Cythonizing sklearn\_loss\_loss.pyx
      [ 4/64] Cythonizing sklearn\cluster\_dbscan_inner.pyx
      [ 5/64] Cythonizing sklearn\cluster\_hierarchical_fast.pyx
      [ 6/64] Cythonizing sklearn\cluster\_k_means_common.pyx
      [ 7/64] Cythonizing sklearn\cluster\_k_means_elkan.pyx
      [ 8/64] Cythonizing sklearn\cluster\_k_means_lloyd.pyx
      [ 9/64] Cythonizing sklearn\cluster\_k_means_minibatch.pyx
      [10/64] Cythonizing sklearn\datasets\_svmlight_format_fast.pyx
      [11/64] Cythonizing sklearn\decomposition\_cdnmf_fast.pyx
      [12/64] Cythonizing sklearn\decomposition\_online_lda_fast.pyx
      [13/64] Cythonizing sklearn\ensemble\_gradient_boosting.pyx
      [14/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\_binning.pyx
      [15/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\_bitset.pyx
      [16/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\_gradient_boosting.pyx
      [17/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\_predictor.pyx
      [18/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\common.pyx
      [19/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\histogram.pyx
      [20/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\splitting.pyx
      [21/64] Cythonizing sklearn\ensemble\_hist_gradient_boosting\utils.pyx
      [22/64] Cythonizing sklearn\feature_extraction\_hashing_fast.pyx
      [23/64] Cythonizing sklearn\linear_model\_cd_fast.pyx
      [24/64] Cythonizing sklearn\linear_model\_sag_fast.pyx
      [25/64] Cythonizing sklearn\linear_model\_sgd_fast.pyx
      [26/64] Cythonizing sklearn\manifold\_barnes_hut_tsne.pyx
      [27/64] Cythonizing sklearn\manifold\_utils.pyx
      [28/64] Cythonizing sklearn\metrics\_dist_metrics.pyx
      [29/64] Cythonizing sklearn\metrics\_pairwise_distances_reduction\_argkmin.pyx
      [30/64] Cythonizing sklearn\metrics\_pairwise_distances_reduction\_base.pyx
      [31/64] Cythonizing sklearn\metrics\_pairwise_distances_reduction\_datasets_pair.pyx
      [32/64] Cythonizing sklearn\metrics\_pairwise_distances_reduction\_middle_term_computer.pyx
      [33/64] Cythonizing sklearn\metrics\_pairwise_distances_reduction\_radius_neighbors.pyx
      [34/64] Cythonizing sklearn\metrics\_pairwise_fast.pyx
      [35/64] Cythonizing sklearn\metrics\cluster\_expected_mutual_info_fast.pyx
      [36/64] Cythonizing sklearn\neighbors\_ball_tree.pyx
      [37/64] Cythonizing sklearn\neighbors\_kd_tree.pyx
      [38/64] Cythonizing sklearn\neighbors\_partition_nodes.pyx
      [39/64] Cythonizing sklearn\neighbors\_quad_tree.pyx
      [40/64] Cythonizing sklearn\preprocessing\_csr_polynomial_expansion.pyx
      [41/64] Cythonizing sklearn\svm\_liblinear.pyx
      [42/64] Cythonizing sklearn\svm\_libsvm.pyx
      [43/64] Cythonizing sklearn\svm\_libsvm_sparse.pyx
      [44/64] Cythonizing sklearn\svm\_newrand.pyx
      [45/64] Cythonizing sklearn\tree\_criterion.pyx
      [46/64] Cythonizing sklearn\tree\_splitter.pyx
      [47/64] Cythonizing sklearn\tree\_tree.pyx
      [48/64] Cythonizing sklearn\tree\_utils.pyx
      [49/64] Cythonizing sklearn\utils\_cython_blas.pyx
      [50/64] Cythonizing sklearn\utils\_fast_dict.pyx
      [51/64] Cythonizing sklearn\utils\_heap.pyx
      [52/64] Cythonizing sklearn\utils\_isfinite.pyx
      [53/64] Cythonizing sklearn\utils\_logistic_sigmoid.pyx
      [54/64] Cythonizing sklearn\utils\_openmp_helpers.pyx
      [55/64] Cythonizing sklearn\utils\_random.pyx
      [56/64] Cythonizing sklearn\utils\_readonly_array_wrapper.pyx
      [57/64] Cythonizing sklearn\utils\_seq_dataset.pyx
      [58/64] Cythonizing sklearn\utils\_sorting.pyx
      [59/64] Cythonizing sklearn\utils\_typedefs.pyx
      [60/64] Cythonizing sklearn\utils\_vector_sentinel.pyx
      [61/64] Cythonizing sklearn\utils\_weight_vector.pyx
      [62/64] Cythonizing sklearn\utils\arrayfuncs.pyx
      [63/64] Cythonizing sklearn\utils\murmurhash.pyx
      [64/64] Cythonizing sklearn\utils\sparsefuncs_fast.pyx
          main()
        File "C:\Users\Rion Dey\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Rion Dey\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 669, in <module>
        File "<string>", line 663, in setup_package
        File "<string>", line 597, in configure_extension_modules
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-install-1oddo018\scikit-learn_08cd4695a5de42cb901570f034c6e16a\sklearn\_build_utils\__init__.py", line 98, in cythonize_extensions
          return cythonize(
                 ^^^^^^^^^^
        File "C:\Users\Rion Dey\AppData\Local\Temp\pip-build-env-ai8_x5xu\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1145, in cythonize
          result.get(99999)  # seconds
          ^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\miniconda3\Lib\multiprocessing\pool.py", line 774, in get
          raise self._value
      Cython.Compiler.Errors.CompileError: sklearn\_loss\_loss.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Rion-beta-development** [comment]
does anyone know how to fix this

**Comment by Rion-beta-development** [comment]
Bro we can try using comfyui manager

**Comment by Rion-beta-development** [comment]
I have a solution install miniconda and use it instead of CMD
