### ISSUE TITLE
RuntimeError: No GPU found. A GPU is needed for quantization.

### ISSUE THREAD

**Issue by xdyeahcomon** [magic-quill/ComfyUI_MagicQuill#17]
Got this error, how I can solve this?
```
Prestartup times for custom nodes:
   8.8 seconds: C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16308 MB, total RAM 16308 MB
pytorch version: 2.4.1+cpu
Set vram state to: DISABLED
Disabling smart memory management
Device: cpu
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.7-33-g6d1a3f7 | Released on '2024-12-15'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
['C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\comfy', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded\\python312.zip', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded', 'C:\\Users\\W11\\AppData\\Roaming\\Python\\Python312\\site-packages', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\win32', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\win32\\lib', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\Pythonwin', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\glob', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\glob', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\glob', '../..', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_controlnet_aux', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_MagicQuill', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes', 'C:\\Users\\W11\\Downloads\\COMFYUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras']
Traceback (most recent call last):
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\__init__.py", line 20, in <module>
    from .magic_quill import MagicQuill
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\magic_quill.py", line 104, in <module>
    class MagicQuill(object):
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\magic_quill.py", line 106, in MagicQuill
    llavaModel = LLaVAModel()
                 ^^^^^^^^^^^^
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\llava_new.py", line 29, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
                                                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\LLaVA\llava\model\builder.py", line 122, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3030, in from_pretrained
    raise RuntimeError("No GPU found. A GPU is needed for quantization.")
RuntimeError: No GPU found. A GPU is needed for quantization.

Cannot import C:\Users\W11\Downloads\COMFYUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill module for custom nodes: No GPU found. A GPU is needed for quantization.
```

**Comment by brantje** [comment]
Well... maybe install a GPU :')?
