### ISSUE TITLE
Problem with loading LLaVaModel()

### ISSUE THREAD

**Issue by Burve** [magic-quill/ComfyUI_MagicQuill#2]
Hi, after installing multiple dependencies, I encountered this error. It looks like there are conflicting arguments in the plugin code when trying to load the LLaVa model.

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\__init__.py", line 20, in <module>
    from .magic_quill import MagicQuill
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\magic_quill.py", line 104, in <module>
    class MagicQuill(object):
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\magic_quill.py", line 106, in MagicQuill
    llavaModel = LLaVAModel()
                 ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\llava_new.py", line 29, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
                                                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\LLaVA\llava\model\builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3325, in from_pretrained
    raise ValueError(
ValueError: You can't pass `load_in_4bit`or `load_in_8bit` as a kwarg when passing `quantization_config` argument at the same time.

**Comment by zliucz** [comment]
Hi, please try to re-install transformers by
```
pip install transformers==4.37.2
```

Thanks.

**Comment by Aljnk** [comment]
if i can't downgrade `transformers` what should i do?
