### ISSUE TITLE
No module named 'ComfyUI_BrushNet'

### ISSUE THREAD

**Issue by ShineHe2023** [magic-quill/ComfyUI_MagicQuill#5]
But I have installed ComfyUI_BrushNet correctly

**Comment by zliucz** [comment]
Hi :). Please rename the `ComfyUI-BrushNet` folder to `ComfyUI_BrushNet`. This is because the Python import doesn't allow package with string `-`.

**Comment by ShineHe2023** [comment]
> Hi :). Please rename the `ComfyUI-BrushNet` folder to `ComfyUI_BrushNet`. This is because the Python import doesn't allow package with string `-`.

No module named 'model.llava_arch'

**Comment by zliucz** [comment]
Would you please pull the latest code to see if it works now?

**Comment by ShineHe2023** [comment]
> Would you please pull the latest code to see if it works now?

Cannot import /home/ComfyUI/custom_nodes/ComfyUI_MagicQuill module for custom nodes: Incorrect path_or_model_id: '/home/ComfyUI/models/llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by zliucz** [comment]
Hi, please place the `llava-v1.5-7b-finetune-clean` checkpoint folder at `/home/ComfyUI/models`.

**Comment by ShineHe2023** [comment]
> Hi, please place the `llava-v1.5-7b-finetune-clean` checkpoint folder at `/home/ComfyUI/models`.

NameError: name 'LlavaLlamaForCausalLM' is not defined

Cannot import /home/ComfyUI/custom_nodes/ComfyUI_MagicQuill module for custom nodes: name 'LlavaLlamaForCausalLM' is not defined

**Comment by ShineHe2023** [comment]
NameError: name 'sys' is not defined

Cannot import /home/ComfyUI/custom_nodes/ComfyUI_MagicQuill module for custom nodes: name 'sys' is not defined

**Comment by zliucz** [comment]
Hi, may I get the detailed error log? I need to know where did you get this error. Typically, just include `import sys` on that file's header shall solve the problem.

**Comment by ShineHe2023** [comment]
> Fixed. Please pull the latest code.

感谢

**Comment by mykeehu** [comment]
I got this error after doing the above:
```
Traceback (most recent call last):
  File "I:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2113, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\__init__.py", line 20, in <module>
    from .magic_quill import MagicQuill
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\magic_quill.py", line 104, in <module>
    class MagicQuill(object):
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\magic_quill.py", line 106, in MagicQuill
    llavaModel = LLaVAModel()
                 ^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\llava_new.py", line 29, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
                                                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill\LLaVA\llava\model\builder.py", line 122, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3596, in from_pretrained
    raise ValueError(
ValueError: You can't pass `load_in_4bit`or `load_in_8bit` as a kwarg when passing `quantization_config` argument at the same time.

Cannot import I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicQuill module for custom nodes: You can't pass `load_in_4bit`or `load_in_8bit` as a kwarg when passing `quantization_config` argument at the same time.
```
